# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-28 08:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_name', models.CharField(max_length=100)),
                ('report_type', models.PositiveSmallIntegerField()),
                ('period', models.PositiveSmallIntegerField()),
                ('sendto_name', models.CharField(max_length=100)),
                ('sendto_address', models.CharField(max_length=100)),
                ('appriesto_product', models.CharField(max_length=100)),
                ('appriesto_attribute', models.CharField(max_length=100)),
                ('condition_index', models.CharField(max_length=100)),
                ('condition_command', models.PositiveSmallIntegerField()),
                ('condition_vale', models.PositiveSmallIntegerField()),
                ('created_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='created time')),
                ('updated_time', models.DateTimeField(auto_now=True, null=True, verbose_name='updated time')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
