# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-28 09:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertsetting',
            name='appriesto_attribute',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='alertsetting',
            name='appriesto_product',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
